package tools

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"bytes"

	"github.com/platform-api/mcp-server/config"
	"github.com/platform-api/mcp-server/models"
	"github.com/mark3labs/mcp-go/mcp"
)

func PatchpushdevicedetailsHandler(cfg *config.APIConfig) func(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args, ok := request.Params.Arguments.(map[string]any)
		if !ok {
			return mcp.NewToolResultError("Invalid arguments object"), nil
		}
		device_idVal, ok := args["device_id"]
		if !ok {
			return mcp.NewToolResultError("Missing required path parameter: device_id"), nil
		}
		device_id, ok := device_idVal.(string)
		if !ok {
			return mcp.NewToolResultError("Invalid path parameter: device_id"), nil
		}
		// Create properly typed request body using the generated schema
		var requestBody models.DeviceDetails
		
		// Optimized: Single marshal/unmarshal with JSON tags handling field mapping
		if argsJSON, err := json.Marshal(args); err == nil {
			if err := json.Unmarshal(argsJSON, &requestBody); err != nil {
				return mcp.NewToolResultError(fmt.Sprintf("Failed to convert arguments to request type: %v", err)), nil
			}
		} else {
			return mcp.NewToolResultError(fmt.Sprintf("Failed to marshal arguments: %v", err)), nil
		}
		
		bodyBytes, err := json.Marshal(requestBody)
		if err != nil {
			return mcp.NewToolResultErrorFromErr("Failed to encode request body", err), nil
		}
		url := fmt.Sprintf("%s/push/deviceRegistrations/%s", cfg.BaseURL, device_id)
		req, err := http.NewRequest("PATCH", url, bytes.NewBuffer(bodyBytes))
		req.Header.Set("Content-Type", "application/json")
		if err != nil {
			return mcp.NewToolResultErrorFromErr("Failed to create request", err), nil
		}
		// Set authentication based on auth type
		if cfg.BasicAuth != "" {
			req.Header.Set("Authorization", fmt.Sprintf("Basic %s", cfg.BasicAuth))
		}
		req.Header.Set("Accept", "application/json")

		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			return mcp.NewToolResultErrorFromErr("Request failed", err), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultErrorFromErr("Failed to read response body", err), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("API error: %s", body)), nil
		}
		// Use properly typed response
		var result models.Error
		if err := json.Unmarshal(body, &result); err != nil {
			// Fallback to raw text if unmarshaling fails
			return mcp.NewToolResultText(string(body)), nil
		}

		prettyJSON, err := json.MarshalIndent(result, "", "  ")
		if err != nil {
			return mcp.NewToolResultErrorFromErr("Failed to format JSON", err), nil
		}

		return mcp.NewToolResultText(string(prettyJSON)), nil
	}
}

func CreatePatchpushdevicedetailsTool(cfg *config.APIConfig) models.Tool {
	tool := mcp.NewTool("patch_push_deviceRegistrations_device_id",
		mcp.WithDescription("Update a device registration"),
		mcp.WithString("device_id", mcp.Required(), mcp.Description("Device's ID.")),
		mcp.WithString("deviceSecret", mcp.Description("Input parameter: Secret value for the device.")),
		mcp.WithString("formFactor", mcp.Description("Input parameter: Form factor of the push device.")),
		mcp.WithString("id", mcp.Description("Input parameter: Unique identifier for the device generated by the device itself.")),
		mcp.WithObject("metadata", mcp.Description("Input parameter: Optional metadata object for this device. The metadata for a device may only be set by clients with push-admin privileges and will be used more extensively in the future with smart notifications.")),
		mcp.WithString("platform", mcp.Description("Input parameter: Platform of the push device.")),
		mcp.WithObject("push.recipient", mcp.Description("Input parameter: Push recipient details for a device.")),
		mcp.WithString("push.state", mcp.Description("Input parameter: the current state of the push device.")),
		mcp.WithString("clientId", mcp.Description("Input parameter: Optional trusted client identifier for the device.")),
	)

	return models.Tool{
		Definition: tool,
		Handler:    PatchpushdevicedetailsHandler(cfg),
	}
}
